/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.tests

import com.google.inject.Inject
import de.uniba.swt.dsl.bahn.RootModule
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(BahnInjectorProvider)
class BahnParsingTest {
	
	@Inject extension ParseHelper<RootModule>
	@Inject extension ParserTestHelper
	
	@Test
	def void loadModel() {
		'''
			module lite end
		'''.parse.assertNoParsingErrors
	}
	
	@Test
	def void testErrorMissingEnd() {
		'''
			module expr
				boards
			end
		'''.parse.assertParsingError("expecting 'end'")
	}
	
	@Test
	def void testBehaviourSyntacticSugar() {
		'''
			module expr
				def inter()
					# grant route
					grant route1 to cargo_green

					# set aspect
					set signal sig1 to red
					set point point1 to normal
					set point point1 to reverse

					# get aspect
					var pAspect = get point point1
					var sAspect = get signal sig1

					# check aspect
					bool isRed = get signal sig1 is red
					bool isNotNormal = get point point1 is not normal

					# wait
					wait for 3 seconds

					# segment occupied
					bool so1 = seg1 is occupied
					bool so2 = seg1 is not occupied

					# segment occupied by train
					bool s1 = seg1 is occupied by train
					bool s2 = seg1 is not occupied by train

					# route available
					bool r1 = route1 is available
					bool r2 = route1 is not available

					# get route
					var route1 = get route from sig1 to sig2
				end
			end
		'''.parse.assertNoParsingErrors
	}
}
