/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import de.uniba.swt.dsl.bahn.RootModule

@ExtendWith(InjectionExtension)
@InjectWith(BahnInjectorProvider)
class FuncDeclParsingTest {
	
	@Inject extension ParseHelper<RootModule>
	@Inject extension ParserTestHelper

	@Test
	def void testSingleFuncDecl() {
		'''
			module test
				def test1()
				end
			end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testSingleWithParamsFuncDecl() {
		'''
			module test
				def test1(int a, var list)
				end
			end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testMultipleFuncDecl() {
		'''
			module test
				def test1()
				end
				def test2()
				end
			end
		'''.parse.assertNoParsingErrors
	}
}
