/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ide

import com.google.inject.Guice
import de.uniba.swt.dsl.BahnDSLRuntimeModule
import de.uniba.swt.dsl.BahnDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BahnDSLIdeSetup extends BahnDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BahnDSLRuntimeModule, new BahnDSLIdeModule))
	}
	
}
