/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BahnExprUiModule extends AbstractBahnExprUiModule {

	public BahnExprUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
