/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.uniba.swt.expr.BahnExprRuntimeModule;
import de.uniba.swt.expr.BahnExprStandaloneSetup;
import de.uniba.swt.expr.ide.BahnExprIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class BahnExprWebSetup extends BahnExprStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BahnExprRuntimeModule(), new BahnExprIdeModule(), new BahnExprWebModule()));
	}
	
}
