/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.uniba.swt.expr.BahnExprRuntimeModule;
import de.uniba.swt.expr.BahnExprStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BahnExprIdeSetup extends BahnExprStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BahnExprRuntimeModule(), new BahnExprIdeModule()));
	}
	
}
