/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.generator;

import de.uniba.swt.dsl.normalization.BahnNormalizationProvider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import com.google.inject.Inject;

import de.uniba.swt.dsl.bahn.RootModule;
import de.uniba.swt.dsl.common.generator.yaml.BidibYamlConfigGenerator;
import de.uniba.swt.dsl.common.models.NetworkModel;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class BahnGenerator extends AbstractGenerator {
	
	@Inject 
	BidibYamlConfigGenerator bidibGenerator;
	
	@Inject
	ModelConverter modelConverter;

	@Inject
	BahnNormalizationProvider normalizationProvider;

	@Override
	public void beforeGenerate(Resource input, IFileSystemAccess2 fsa, IGeneratorContext context) {
		RootModule rootModule = getRootModule(input);
		if (rootModule != null) {
			normalizationProvider.normalize(rootModule);
		}
	}

	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		RootModule rootModule = getRootModule(resource);
		if (rootModule != null) {
			NetworkModel network = modelConverter.buildNetworkModel(rootModule);
			
			// bidib_board_config
			fsa.generateFile("bidib_board_config.yml", bidibGenerator.dumpBoardConfig(network.name, network.boards));
			
			// bidib_track_config
			fsa.generateFile("bidib_track_config.yml", bidibGenerator.dumpTrackConfig(network));
			
			// bidib_train_config
			fsa.generateFile("bidib_train_config.yml", bidibGenerator.dumpTrainConfig(network.name, network.trains));

			// ast
			String name = (rootModule.getName());
			fsa.generateFile(name + "_ast.txt", AstGenerator.dumpAst(resource.getContents().get(0), ""));
		}
	}

	private RootModule getRootModule(Resource resource) {
		EObject e = resource.getContents().get(0);
		if (e instanceof RootModule)
			return (RootModule)e;

		return null;
	}
}
