/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BahnExprStandaloneSetup extends BahnExprStandaloneSetupGenerated {

	public static void doSetup() {
		new BahnExprStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
