/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr;


import de.uniba.swt.expr.converter.BahnExprValueConverterService;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BahnExprRuntimeModule extends AbstractBahnExprRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return BahnExprValueConverterService.class;
    }
}
