/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import org.eclipse.xtext.ui.wizard.template.DefaultTemplateProjectCreator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BahnUiModule extends AbstractBahnUiModule {

	public BahnUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.ui.projectWizard.TemplateProjectWizardFragment
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return DefaultTemplateProjectCreator.class;
	}
}
