/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BahnUiModule extends AbstractBahnUiModule {

	public BahnUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
