/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BahnStandaloneSetup extends BahnStandaloneSetupGenerated {

	public static void doSetup() {
		new BahnStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
