/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.tests

import com.google.inject.Inject
import de.uniba.swt.dsl.bahn.ModuleObject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(BahnInjectorProvider)
class BahnFuncDeclParsingTest {
	@Inject
	ParseHelper<ModuleObject> parseHelper
	
	@Test
	def void testFuncDeclsProperty() {
		val result = parseHelper.parse('''
			module expr
				def inter()

				end
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testIfStmtProperty() {
		val result = parseHelper.parse('''
			module expr
				def inter()
					int input = 0
					if true
						input = 1
					else
						input = 2
					end
				end
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
