/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import de.uniba.swt.dsl.bahn.RootModule

@ExtendWith(InjectionExtension)
@InjectWith(BahnInjectorProvider)
class FunctionCallExprParsingTest {
	
	@Inject extension ParseHelper<RootModule>
	@Inject extension ParserTestHelper

	@Test
	def void testEmptyFunctionCallExpr() {
		'''
			module test def test()
				var routes1 = getAllRoutes()
			end end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testSingleParamFunctionCallExpr() {
		'''
			module test def test()
				var route1 = getRoute(routeId)
			end end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testParamsFunctionCallExpr() {
		'''
			module test def test()
				var route1 = getRouteFromTable(table, signal1, signal2)
			end end
		'''.parse.assertNoParsingErrors
	}
}
