/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import de.uniba.swt.dsl.bahn.RootModule

@ExtendWith(InjectionExtension)
@InjectWith(BahnInjectorProvider)
class VariableParsingTest {
	
	@Inject extension ParseHelper<RootModule>
	@Inject extension ParserTestHelper

	@Test
	def void testScalarVarDeclStmt() {
		'''
			module test
			def test()
			        int a = 3
			        float b = 4.5
			        bool c = true
			    end
			end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testArrayVarDeclStmt() {
		'''
			module test
			    def test()
			        int a[2] = {3,4}
			        float b[1+ 2] = {4.5, 2, 4}
			        bool c[1] = {true}
			    end
			end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testScalarAssignmentStmt() {
		'''
			module test
			    def test()
			        a = 3
			        b = 4.5
			        c = true
			    end
			end
		'''.parse.assertNoParsingErrors
	}

	@Test
	def void testArrayAssignmentStmt() {
		'''
			module test
			    def test()
			        a[2] = {3,4}
			        b[1+ 2] = {4.5, 2, 4}
			        c[1] = {true}
			    end
			end
		'''.parse.assertNoParsingErrors
	}
}
