/*
 * This file is part of the BahnDSL project, a domain-specific language
 * for configuring and modelling model railways
 *
 * BahnDSL is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BahnDSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with BahnDSL.  If not, see <https://www.gnu.org/licenses/>.
 *
 * The following people contributed to the conception and realization of the
 * present BahnDSL (in alphabetic order by surname):
 *
 * - Tri Nguyen <https://github.com/trinnguyen>
 */

/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.generator;

import de.uniba.swt.dsl.bahn.FuncDecl;
import de.uniba.swt.dsl.common.generator.sccharts.SCChartsGenerator;
import de.uniba.swt.dsl.common.generator.yaml.YamlConfigGenerator;
import de.uniba.swt.dsl.common.util.BahnUtil;
import de.uniba.swt.dsl.normalization.BahnNormalizationProvider;
import de.uniba.swt.dsl.validation.validators.SwtBahnFuncValidator;
import org.apache.log4j.Logger;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

import com.google.inject.Inject;

import de.uniba.swt.dsl.common.layout.LayoutGenerator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
public class BahnGenerator extends AbstractGenerator {

	private static final Logger logger = Logger.getLogger(BahnGenerator.class);

	@Inject
	BahnNormalizationProvider normalizationProvider;

	@Inject
	YamlConfigGenerator yamlConfigGenerator;

	@Inject
	SCChartsGenerator scChartsGenerator;
	
	@Inject
	LayoutGenerator layoutGenerator;

	@Inject
	SwtBahnFuncValidator swtBahnFuncValidator;

	@Override
	public void beforeGenerate(Resource input, IFileSystemAccess2 fsa, IGeneratorContext context) {
		var decls = BahnUtil.getDecls(input);
		if (decls == null || decls.size() == 0)
			return;

		// check required function
		checkInterlockingFunctions(input);

		// normalize
		normalizationProvider.normalize(BahnUtil.getDecls(input.getResourceSet()));
	}

	@Override
	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		var bahnModel = BahnUtil.getBahnModel(resource);
		if (bahnModel == null)
			return;

		// layout generator must run first to generate network layout
		layoutGenerator.generate(fsa, bahnModel);

		// use network layout for block generation (direction, signals)
		yamlConfigGenerator.setNetworkLayout(layoutGenerator.getNetworkLayout());
		yamlConfigGenerator.generate(fsa, bahnModel);

		// sccharts
		scChartsGenerator.generate(fsa, bahnModel);
	}

	private void checkInterlockingFunctions(Resource resource) {
		var bahnModel = BahnUtil.getBahnModel(resource);

		var result = swtBahnFuncValidator.hasRequestAndDriveRoute(bahnModel);
		if (!result.getFirst()) {
			logger.error("Missing function for requesting route. SCCharts code generation is skipped.");
			return;
		}

		if (!result.getSecond()) {
			logger.warn("Adding empty driving route function");
			FuncDecl decl = swtBahnFuncValidator.generateDriveRouteFuncDecl();
			bahnModel.getComponents().add(decl);
		}
	}
}
