/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class BahnProposalProvider extends AbstractBahnProposalProvider {
}
