/**
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ui.wizard;

import de.uniba.swt.dsl.ui.wizard.SampleBahnProject;
import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.IProjectTemplateProvider;

/**
 * Create a list with all project templates to be shown in the template new project wizard.
 * 
 * Each template is able to generate one or more projects. Each project can be configured such that any number of files are included.
 */
@SuppressWarnings("all")
public class BahnProjectTemplateProvider implements IProjectTemplateProvider {
  @Override
  public AbstractProjectTemplate[] getProjectTemplates() {
    SampleBahnProject project = new SampleBahnProject();
    return new AbstractProjectTemplate[] { project };
  }
}
