/**
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ui.wizard;

import de.uniba.swt.dsl.ui.wizard.BahnModelFile;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileTemplateProvider;

/**
 * Create a list with all file templates to be shown in the template new file wizard.
 * 
 * Each template is able to generate one or more files.
 */
@SuppressWarnings("all")
public class BahnFileTemplateProvider implements IFileTemplateProvider {
  @Override
  public AbstractFileTemplate[] getFileTemplates() {
    BahnModelFile file = new BahnModelFile();
    return new AbstractFileTemplate[] { file };
  }
}
