/**
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.ui.wizard;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.ui.wizard.template.AbstractFileTemplate;
import org.eclipse.xtext.ui.wizard.template.FileTemplate;
import org.eclipse.xtext.ui.wizard.template.IFileGenerator;

@FileTemplate(label = "Bahn Model", icon = "file_template.png", description = "Create a Bahn model")
@SuppressWarnings("all")
public final class BahnModelFile extends AbstractFileTemplate {
  @Override
  public void generateFiles(final IFileGenerator generator) {
    String path = String.format("%s/%s.bahn", getFolder(), getName());
    generator.generate(path, BahnUiSnippet.EmptyBahnSource);
  }
}
