/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class BahnWebModule extends AbstractBahnWebModule {
}
