/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.uniba.swt.dsl.BahnRuntimeModule;
import de.uniba.swt.dsl.BahnStandaloneSetup;
import de.uniba.swt.dsl.ide.BahnIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class BahnWebSetup extends BahnStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BahnRuntimeModule(), new BahnIdeModule(), new BahnWebModule()));
	}
	
}
