/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import de.uniba.swt.expr.bahnexpr.BahnExpr
import org.eclipse.xtext.testing.validation.ValidationTestHelper

@ExtendWith(InjectionExtension)
@InjectWith(BahnExprInjectorProvider)
class BahnExprParsingTest {
	@Inject extension ParseHelper<BahnExpr>
	@Inject extension ValidationTestHelper

	@Test
	def void testStatementList() {
		'''
			def sum(int a, int b)
				int c = a + b
				return c
			end

			def main()
				return sum(3, 4)
			end
		'''.parse.assertNoErrors
	}
}
