/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import de.uniba.swt.expr.bahnexpr.BahnExpr

@ExtendWith(InjectionExtension)
@InjectWith(BahnExprInjectorProvider)
class ExpressionParsingTest {
	@Inject
	ParseHelper<BahnExpr> parseHelper

	@Test
	def void testLogicalOrExpr() {
		val result = parseHelper.parse('''
			def test()
				bool result = true || false
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testLogicalAndExpr() {
		val result = parseHelper.parse('''
			def test()
				bool result = true && false
				bool result = true && false || true
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testEqualityExpr() {
		val result = parseHelper.parse('''
			def test()
				bool result1 = 3 == 4
				result1 = 3 != 4
				result2 = true == true
				result3 = true != false
				result4 = 1 == 2
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testEqualityExprReference() {
		val result = parseHelper.parse('''
			def test()
				bool result1 = 3 == 4
				result1 = 3 != 4
				result2 = true == true
				result3 = true != false
				result4 = 1 == 2
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testRelationalExpr() {
		val result = parseHelper.parse('''
			def test()
				bool success = 1 > 2
				success = 1 <= 2
				success = 1 > 2
				success = 1 >= 2
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
	
	@Test
	def void testAdditiveExpr() {
		val result = parseHelper.parse('''
			def test()
				int a = 3 + 4
				int b = 4 - 3
				int c = 3 - 4 +5
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testMultiplicativeExpr() {
		val result = parseHelper.parse('''
			def test()
				int a = 3 * 4
				int b = 4 / 3
				float c = 3 * 4 / 5
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testUnaryExpr() {
		val result = parseHelper.parse('''
			def test()
				bool result = !true
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
    def void testSignedNumber() {
        val result = parseHelper.parse('''
            def test()
                int a = -3
                int a = -4
            end
        ''')
        Assertions.assertNotNull(result)
        val errors = result.eResource.errors
        Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
    }

	@Test
	def void testParenthesizedExpr() {
		val result = parseHelper.parse('''
			def test()
				int a = 5 * (3 + 4)
				bool result = true || (false && true)
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testBooleanLiteral() {
		val result = parseHelper.parse('''
			def test()
				bool result = true
				result = false
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testNumberLiteral() {
		val result = parseHelper.parse('''
			def test()
				int a = 3
				float b = 4.5
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testStringLiteral() {
		val result = parseHelper.parse('''
			def test()
				string aspectRed = "red"
				string aspectReverse = "reverse"
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testValuedReferenceExpr() {
		val result = parseHelper.parse('''
			def test()
				float b = a * 5
				b = a + 5
				b = c || true
				b = d == true
				b = d > 3
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testArrayValuedReferenceExpr() {
		val result = parseHelper.parse('''
			def test()
				float b = a[0] * 5
				b = a[1] + 5
				b = c[2] || true
				b = d[3] == true
				b = d[4] > 3
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

	@Test
	def void testPropertyValuedReferenceExpr() {
		val result = parseHelper.parse('''
			def test()
				float b = a.value * 5
				b = a.value + 5
				b = c.result || true
				b = d.result == true
				b = d.result > 3
			end
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
