/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BahnDSLStandaloneSetup extends BahnDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new BahnDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
