/*
 * generated by Xtext 2.20.0
 */
package de.uniba.swt.expr.validation;


import de.uniba.swt.expr.bahnexpr.Expression;
import de.uniba.swt.expr.bahnexpr.Statement;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class BahnExprValidator extends AbstractBahnExprValidator {

    @Check
    public void typeCheckingExpression(Expression expression) {
        try {
            ExpressionValidator.validate(expression);
        } catch (ValidationException e) {
            error(e.getMessage(), e.getFeature());
        }
    }

    @Check
    public void typeCheckingStatement(Statement statement) {
        try {
            StatementValidator.validate(statement);
        } catch (ValidationException e) {
            error(e.getMessage(), e.getFeature());
        }
    }
}
