name: CI with Gradle/Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build bahnc with Gradle
      run: sh src/build-gradle.sh
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: src/build/*.zip
        retention-days: 1
  
  build-maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build Bahn IDE with Maven
      run: sh src/build-maven-rcp.sh
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: src/build/*.*
        retention-days: 1
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests with Gradle
      run: sh src/build-test.sh
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: src/de.uniba.swt.dsl.tests/build/test-results/test/**/TEST-*.xml
    
