name: CI with Gradle/Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build bahnc with Gradle
      run: sh src/build-gradle.sh
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: src/build/*.zip
        retention-days: 1
  
  build-maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Bahn IDE with Maven
      run: sh src/build-maven-rcp.sh
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: src/build/*.*
        retention-days: 1
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests with Gradle
      run: sh src/build-test.sh
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: src/de.uniba.swt.dsl.tests/build/test-results/test/**/TEST-*.xml
    
  test-cli:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run integration tests against bahnc with system C compiler
      run: sh src/build-test-cli.sh
    - name: Publish Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: src/de.uniba.swt.dsl.cli.tests/build/test-results/test/**/TEST-*.xml
    
