name: CI with Gradle/Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build bahnc with Gradle
      run: sh src/build-gradle.sh
    - uses: actions/upload-artifact@v4
      with:
        name: build-gradle
        path: src/build/*.zip
        retention-days: 1
  
  build-maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Bahn IDE with Maven
      run: sh src/build-maven-rcp.sh
    - uses: actions/upload-artifact@v4
      with:
        name: build-maven
        path: src/build/*.*
        retention-days: 1
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run unit tests with Gradle
      run: sh src/build-test.sh
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Unit Test Results"
        junit_files: src/de.uniba.swt.dsl.tests/build/test-results/test/**/TEST-*.xml
    
  test-cli:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run integration tests against bahnc with system C compiler
      run: sh src/build-test-cli.sh
    - name: Publish Integration Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Integration Test Results"
        junit_files: src/de.uniba.swt.dsl.cli.tests/build/test-results/test/**/TEST-*.xml
    
